### ISSUE TITLE
友链交换w

### ISSUE THREAD

**Issue by IoriMaboroshi** [Isoheptane/isoheptane.github.io#11]
名称：伊緻幻の主页

图标：`https://b.chwin.asia/wp-content/uploads/2022/11/cropped-lab.magiconch.com90s-time-machine-1667800846069.jpg`

域名：`https://www.chwin.asia`

描述：Take my hands.

贴贴w

**Comment by Isoheptane** [comment]
Request approved.
贴贴哦——

**Comment by IoriMaboroshi** [comment]
www
