### ISSUE TITLE
申请友链

### ISSUE THREAD

**Issue by HanamiYuushimo** [Isoheptane/isoheptane.github.io#20]
- 网站名称：幽霜的日常记录
- 网站地址：https://hanamiyuushimo.github.io
- 网站图标或头像：https://hanamiyuushimo.github.io/images/avatar.png
- 描述：「Stay young, stay simple. 」

**Comment by Isoheptane** [comment]
抱歉前几天有点忙，没有及时处理，现在已经加上了哦
