### ISSUE TITLE
申请友链

### ISSUE THREAD

**Issue by SinzMise** [Isoheptane/isoheptane.github.io#24]
- 网站名称：九弦之屋
- 网站地址：https://blog.sinzmise.top/
- 网站图标或头像：https://blog.sinzmise.top/img/avatar.png
- 描述：欢迎旅行者，来到这个平凡但又记载了许多故事的小屋

**Comment by Isoheptane** [comment]
實在抱歉，因為最近忙於其他事情而沒有及時處理您的請求！
我將會馬上處理您的請求。

**Comment by Isoheptane** [comment]
現在加上了您的鏈接了～
