### ISSUE TITLE
九弦之都 友链信息更新

### ISSUE THREAD

**Issue by SinzMise** [Isoheptane/isoheptane.github.io#26]
由于原九弦之都已经改名，麻烦修改一下链接信息：
站点名称：中弦星空魔法屋
站点地址：https://blog.sinzmise.top/
站点描述：种下一颗有故事的种子，让它带着魔法和奇迹生根发芽
站点图像：https://blog.sinzmise.top/img/512.png

**Comment by Isoheptane** [comment]
已經修改完成了！
