### ISSUE TITLE
中弦星空魔法屋 友链信息更新

### ISSUE THREAD

**Issue by SinzMise** [Isoheptane/isoheptane.github.io#32]
因站点重新装修，麻烦贵站修改 中弦星空魔法屋 的信息：
网站名称：汐塔魔法屋
网站链接：https://blog.sinzmise.top/
网站头像：https://blog.sinzmise.top/images/icon.png
网站简介：种下一颗有故事的种子，让它带着魔法和奇迹生根发芽

**Comment by Isoheptane** [comment]
已修改——

**Comment by Isoheptane** [comment]
Done

**Comment by Isoheptane** [comment]
已修改——
